# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings lol testing
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Things to do in Portland - Write the Docs Edition
email: beardofedu@github.com
description: The official guide to exploring Portland as written by a group of Write the Docs attendees.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: beardofedu
github_username:  beardofedu
github_repo: wtd-things
logo: /img/logo-copy.png

defaults:
  -
    scope:
      path: ""
    values:
      layout: "docs"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-feed
  - jekyll-octicons

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - github_for_developers.md
  - book
